version: 3
services:
    proxy:
        ports:
            - 4443:443
        container_name: mtproto-proxy
        restart: always
        volumes:
            - 'proxy-config:/data'
        environment:
            - SECRET=1dbf5c48562888c34c4dab4a97c9e780
        image: 'telegrammessenger/proxy:latest'
